### ISSUE TITLE
Mac OS X installation

### ISSUE THREAD

**Issue by goatandsheep** [graingert/python-clamd#15]
How do I install clamd on Mac OS X?

**Comment by graingert** [comment]
Homebrew? This is a python wrapper, not the clamd project

**Comment by graingert** [comment]
This library works over the tcp socket so you can run clamd in docker or a VM

**Comment by graingert** [comment]
http://www.brewformulas.org/Clamav

**Comment by graingert** [comment]
https://gist.github.com/yildizib/fa0effe0ee48f24d9f37

**Comment by goatandsheep** [comment]
perfect! thanks! I tried running `brew install clamav-daemon` that's why it wasn't working. You are awesome!
