### ISSUE TITLE
LGPL Version for clamd

### ISSUE THREAD

**Issue by aminland** [graingert/python-clamd#5]
The license for the library is specified simply as LGPL, but with no version provided. Given that the original pyClamd version 2.0 that you forked from was GPLv2, I'm assuming that you intended for this library to be LGPLv2? Or is it to be going the route of the original pyClamd which switched to LGPLv3 as of version 2.1?

**Comment by ghost** [comment]
Note that this license also states that all copies of the software *must* include a copy of the license, or they are legally unredistributable. This includes the PyPI release.
